###
POST http://localhost:5050/api/regis
Content-Type: application/json

{
    "email": "amban024@gmail.com",
    "password": "4mb4n024"
}
###
GET http://localhost:5050/api/lihat-surat-ket-ktp-menunggu